// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/chatcontext"
	"api/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatContextDelete is the builder for deleting a ChatContext entity.
type ChatContextDelete struct {
	config
	hooks    []Hook
	mutation *ChatContextMutation
}

// Where appends a list predicates to the ChatContextDelete builder.
func (ccd *ChatContextDelete) Where(ps ...predicate.ChatContext) *ChatContextDelete {
	ccd.mutation.Where(ps...)
	return ccd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ccd *ChatContextDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ccd.sqlExec, ccd.mutation, ccd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ccd *ChatContextDelete) ExecX(ctx context.Context) int {
	n, err := ccd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ccd *ChatContextDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chatcontext.Table, sqlgraph.NewFieldSpec(chatcontext.FieldID, field.TypeInt))
	if ps := ccd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ccd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ccd.mutation.done = true
	return affected, err
}

// ChatContextDeleteOne is the builder for deleting a single ChatContext entity.
type ChatContextDeleteOne struct {
	ccd *ChatContextDelete
}

// Where appends a list predicates to the ChatContextDelete builder.
func (ccdo *ChatContextDeleteOne) Where(ps ...predicate.ChatContext) *ChatContextDeleteOne {
	ccdo.ccd.mutation.Where(ps...)
	return ccdo
}

// Exec executes the deletion query.
func (ccdo *ChatContextDeleteOne) Exec(ctx context.Context) error {
	n, err := ccdo.ccd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chatcontext.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ccdo *ChatContextDeleteOne) ExecX(ctx context.Context) {
	if err := ccdo.Exec(ctx); err != nil {
		panic(err)
	}
}
