// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFirstModel() {
  return window['go']['main']['App']['GetFirstModel']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}
