// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ollama} from '../models';
import {main} from '../models';

export function GetFirstModel():Promise<ollama.LocalModel>;

export function GetModels():Promise<Array<ollama.LocalModel>>;

export function SendMessage(arg1:string,arg2:ollama.ModelOptions,arg3:Array<number>,arg4:string):Promise<main.Response>;
