// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {routes} from '../models';
import {ollama} from '../models';

export function GetChatMessages(arg1:number):Promise<any>;

export function GetChats(arg1:number,arg2:number):Promise<routes.Pagination[[]*api/ent>;

export function GetFirstModel():Promise<ollama.LocalModel>;

export function GetModels():Promise<Array<ollama.LocalModel>>;

export function GetOllamaServerUrl():Promise<string>;

export function IsOllamaInstalled():Promise<boolean>;

export function IsOllamaRunning():Promise<boolean>;

export function OpenDirectoryDialog():Promise<Array<string>>;

export function SendMessage(arg1:number,arg2:string,arg3:ollama.ModelOptions,arg4:string):Promise<void>;

export function StartOllama():Promise<void>;
