// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetChats() {
  return window['go']['main']['App']['GetChats']();
}

export function GetFirstModel() {
  return window['go']['main']['App']['GetFirstModel']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetOllamaServerUrl() {
  return window['go']['main']['App']['GetOllamaServerUrl']();
}

export function IsOllamaInstalled() {
  return window['go']['main']['App']['IsOllamaInstalled']();
}

export function IsOllamaRunning() {
  return window['go']['main']['App']['IsOllamaRunning']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function StartOllama() {
  return window['go']['main']['App']['StartOllama']();
}
