version: '3.5'

services:
  supalama_db:
    image: postgres:16.2-alpine
    container_name: supalama_db
    restart: unless-stopped
    env_file:
      - ".env"
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres/${DB_NAME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

networks:
  bs_net:
    name: bs_net